### ISSUE TITLE
Include 2.0.0 review comments

### ISSUE THREAD

**Issue by phoe** [sharplispers/split-sequence#14]
Use a subtype of `PROGRAM-ERROR` in condition signaling

_Originally posted by @sirherrbatka in https://github.com/sharplispers/split-sequence/pull/13/files/c1a4b2f1cd80cd0e0881f3073778b1a7c4b4ed21_

----

`CHECK-TESTS` should be a macro

_Originally posted by @sirherrbatka in https://github.com/sharplispers/split-sequence/pull/13/files/c1a4b2f1cd80cd0e0881f3073778b1a7c4b4ed21_

----

Maybe deinline `CHECK-BOUNDS`, `CHECK-TESTS`, `LIST-LONG-ENOUGH-P`

_Originally posted by @sirherrbatka in https://github.com/sharplispers/split-sequence/pull/13/files/c1a4b2f1cd80cd0e0881f3073778b1a7c4b4ed21_

**Comment by sionescu** [comment]
PR #15 was merged.
