### ISSUE TITLE
CLISP support

### ISSUE THREAD

**Issue by Ragnaroek** [sharplispers/split-sequence#20]
Hi, I get this error in clisp when I'm trying to load usocket (which depends on split-sequence)

85,851 bytes in 0.05 seconds (1782.48KB/sec)
; Loading "usocket"

*** - Error while trying to load definition for system split-sequence from pathname /Users/mb/quicklisp/dists/quicklisp/software/split-sequence-v2.0.0/split-sequence.asd:
      MAKE-INSTANCE: illegal keyword/value pair :IF-FEATURE, (:OR :SBCL :ABCL) in argument list.
      The allowed keywords are (:NAME :VERSION :DESCRIPTION :LONG-DESCRIPTION :IN-ORDER-TO :DO-FIRST :PARENT
      :PATHNAME :AROUND-COMPILE :ENCODING :PROPERTIES :TYPE)

Is CLISP supported? I know it is old and unmaintained, but https://github.com/Ragnaroek/dandelion still supports it and it is sometimes used in education.

**Comment by sionescu** [comment]
split-sequence requires an up-to-date version of ASDF (at least 3.1). I imagine the one bundled with Clisp is too old.
