### ISSUE TITLE
Question : can you illustrate a call to (split-sequence with :test  or :test-not

### ISSUE THREAD

**Issue by vin-d** [sharplispers/split-sequence#21]
Hi,
as a beginner in lisp I have a hard time figuring out a concrete example of split-sequence using the :test or :test keys

Can someone illustrate it with this example ?
```
(split-sequence #\, "foo,bar ,baz, foobar , barbaz,")
⇒ ("foo" "bar " "baz" " foobar " " barbaz" "")
```

Could it be used for example to get the list of words as in the example above but filtering out words that meet a specific criteria
for example words that have a length < 4  ==> this would mean a result of `("foobar" "barbaz")`

 How would you define such a test function ?
Thank you.

**Comment by phoe** [comment]
The `test` and `test-not` keywords are used to check whether a given character should be treated as a delimiter and therefore if and where the sequence should be split.

```lisp
CL-USER> (split-sequence #\a "bacbbAcbaCabAcc" :test #'char=)
("b" "cbbAcb" "C" "bAcc")
15

CL-USER> (split-sequence #\a "bacbbAcbaCabAcc" :test #'char-equal)
("b" "cbb" "cb" "C" "b" "cc")
15

CL-USER> (split-sequence #\a "bacbbAcbaCabAcc" :test-not #'char=)
("" "a" "" "" "" "" "" "a" "a" "" "" "" "")
15

CL-USER> (split-sequence #\a "bacbbAcbaCabAcc" :test-not #'char-equal)
("" "a" "" "" "A" "" "a" "a" "A" "" "")
15
```

These keywords are not meant to be used to filter out the *results* of calling `split-sequence`: for this, you might want to e.g. use `remove-if` or `remove-if-not`.

```lisp
CL-USER> (split-sequence #\, "foo,bar ,baz, foobar , barbaz,")
("foo" "bar " "baz" " foobar " " barbaz" "")
30

CL-USER> (remove-if (lambda (x) (<= (length x) 4)) *)
(" foobar " " barbaz")

;; If we also want to trim spaces from both sides of the string:
CL-USER> (mapcar (lambda (x) (string-trim '(#\Space) x)) *)
("foobar" "barbaz")
```
