### ISSUE TITLE
Metadata for Quicklisp

### ISSUE THREAD

**Issue by hydandata** [sharplispers/split-sequence#3]
Please consider adding :description, :author and :license information to your ASDF system. This will greatly help Quicklisp users and make it easier for them to report bugs.

More information:

http://blog.quicklisp.org/2015/05/looking-for-more-metadata.html
https://www.quicklisp.org

**Comment by luismbo** [comment]
The ASDF system already has this information but it hasn't made it into a proper release yet. Still, thanks for the heads up. :)
